/* ============================================================
   DonutZach — real pack data (from data.js) + interactivity
   ============================================================ */
'use strict';

/* PACKS comes from data.js, generated by build_packs.ps1 */
const PACKS = Array.isArray(window.REAL_PACKS) ? window.REAL_PACKS : [];

/* ---------------- helpers ---------------- */

const $ = (sel, el = document) => el.querySelector(sel);
const $$ = (sel, el = document) => [...el.querySelectorAll(sel)];

const fmtSize = b =>
  b >= 1048576 ? (b / 1048576).toFixed(1).replace(/\.0$/, '') + ' MB'
  : Math.max(1, Math.round(b / 1024)) + ' KB';

function hashStr(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* deterministic palette for packs without a pack.png icon */
function hashPalette(id) {
  const h = hashStr(id) % 360;
  return [
    `hsl(${h} 62% 52%)`,
    `hsl(${h} 55% 34%)`,
    `hsl(${h} 72% 74%)`,
    `hsl(${(h + 145) % 360} 68% 58%)`
  ];
}

/* procedural pixel-art fallback thumbnail */
function drawPackTexture(canvas, pack, cells = 12) {
  const ctx = canvas.getContext('2d');
  const rnd = mulberry32(hashStr(pack.id));
  const [base, dark, light, accent] = hashPalette(pack.id);
  for (let y = 0; y < cells; y++) {
    for (let x = 0; x < cells; x++) {
      const r = rnd();
      ctx.fillStyle = r < 0.5 ? base : r < 0.78 ? dark : light;
      ctx.fillRect(x, y, 1, 1);
    }
  }
  const clusters = 2 + Math.floor(rnd() * 3);
  for (let i = 0; i < clusters; i++) {
    const cx = Math.floor(rnd() * cells);
    const cy = Math.floor(rnd() * cells);
    const n = 3 + Math.floor(rnd() * 3);
    for (let j = 0; j < n; j++) {
      const ox = cx + Math.floor(rnd() * 3) - 1;
      const oy = cy + Math.floor(rnd() * 3) - 1;
      if (ox >= 0 && oy >= 0 && ox < cells && oy < cells) {
        ctx.fillStyle = accent;
        ctx.fillRect(ox, oy, 1, 1);
      }
    }
  }
  ctx.fillStyle = 'rgba(255,255,255,0.16)';
  ctx.fillRect(0, 0, cells, 1);
  ctx.fillStyle = 'rgba(0,0,0,0.38)';
  ctx.fillRect(0, cells - 1, cells, 1);
}

/* ---------------- state ---------------- */

const state = { q: '', cat: 'All', sort: 'az', favOnly: false };

const FAV_KEY = 'donutzach-favs';
let favs = new Set();
try { favs = new Set(JSON.parse(localStorage.getItem(FAV_KEY) || '[]')); } catch (_) { /* private mode */ }
const saveFavs = () => { try { localStorage.setItem(FAV_KEY, JSON.stringify([...favs])); } catch (_) {} };

/* ---------------- toast ---------------- */

const toastEl = $('#toast');
let toastTimer;
function showToast(msg) {
  toastEl.textContent = msg;
  toastEl.hidden = false;
  requestAnimationFrame(() => toastEl.classList.add('show'));
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => {
    toastEl.classList.remove('show');
    setTimeout(() => { toastEl.hidden = true; }, 220);
  }, 2600);
}

/* ---------------- pack grid ---------------- */

const grid = $('#packGrid');
const countEl = $('#resultCount');
const emptyEl = $('#emptyState');

function visiblePacks() {
  const q = state.q.trim().toLowerCase();
  const list = PACKS.filter(p => {
    if (q && !(p.name + ' ' + p.desc + ' ' + p.category).toLowerCase().includes(q)) return false;
    if (state.cat !== 'All' && p.category !== state.cat) return false;
    if (state.favOnly && !favs.has(p.id)) return false;
    return true;
  });
  const s = state.sort;
  list.sort((a, b) =>
    s === 'newest' ? b.ts - a.ts
    : s === 'size-desc' ? b.bytes - a.bytes
    : s === 'size-asc' ? a.bytes - b.bytes
    : a.name.localeCompare(b.name));
  return list;
}

function cardEl(p) {
  const el = document.createElement('article');
  el.className = 'pack-card';
  el.tabIndex = 0;
  el.setAttribute('role', 'button');
  el.setAttribute('aria-haspopup', 'dialog');
  el.setAttribute('aria-label', `${p.name} — open details`);
  const media = p.thumb
    ? `<img class="thumb-img" src="${p.thumb}" alt="" loading="lazy">`
    : `<canvas width="12" height="12" aria-hidden="true"></canvas>`;
  el.innerHTML = `
    <div class="pack-thumb">
      ${media}
      ${p.thumb ? '' : `<span class="pack-emoji" aria-hidden="true">${p.emoji}</span>`}
      <span class="pack-res">${p.res || '—'}</span>
      <button class="fav-toggle" aria-pressed="${favs.has(p.id)}" aria-label="Toggle favorite for ${p.name}" title="Favorite">♥</button>
    </div>
    <div class="pack-body">
      <p class="pack-cat">${p.category} · <span>added ${p.added}</span></p>
      <h3 class="pack-name">${p.name}</h3>
      <p class="pack-desc-short">${p.desc}</p>
      <div class="pack-foot">
        <span class="pack-size" title="File size">📦 ${fmtSize(p.bytes)}</span>
        <a class="btn btn-pixel btn-green btn-mini" href="${p.file}" download="${p.name}.zip" data-dl data-name="${p.name}" aria-label="Download ${p.name}">Get</a>
      </div>
    </div>`;
  if (!p.thumb) drawPackTexture($('canvas', el), p);

  el.addEventListener('click', e => {
    if (e.target.closest('a') || e.target.closest('.fav-toggle')) return;
    openModal(p);
  });
  el.addEventListener('keydown', e => {
    if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openModal(p); }
  });
  $('.fav-toggle', el).addEventListener('click', e => { e.stopPropagation(); toggleFav(p.id); });
  return el;
}

function render() {
  const list = visiblePacks();
  grid.innerHTML = '';
  list.forEach((p, i) => {
    const el = cardEl(p);
    el.classList.add('card-enter');
    el.style.setProperty('--i', Math.min(i, 12));
    grid.appendChild(el);
  });
  emptyEl.hidden = list.length > 0;
  countEl.textContent = `Showing ${list.length} of ${PACKS.length} ${state.favOnly ? 'favorites' : 'packs'}`;
}

/* ---------------- favorites ---------------- */

function toggleFav(id) {
  const added = !favs.has(id);
  favs[added ? 'add' : 'delete'](id);
  saveFavs();
  updateFavUI();
  render();
  showToast(added ? '♥ Added to your favorites' : 'Removed from favorites');
}

function updateFavUI() {
  $('#favCount').textContent = favs.size;
  $('#favBtn').classList.toggle('active', state.favOnly);
  const modalFav = $('#modalFav');
  if (currentPack) {
    modalFav.textContent = favs.has(currentPack.id) ? '♥ Favorited' : '♡ Favorite';
    modalFav.style.borderColor = favs.has(currentPack.id) ? 'var(--pink)' : '';
  }
}

/* ---------------- toolbar ---------------- */

const CATS = ['All', ...new Set(PACKS.map(p => p.category))];
const chipsEl = $('#chips');

function setCat(cat) {
  state.cat = cat;
  $$('.chip', chipsEl).forEach(c => {
    const on = c.textContent === cat;
    c.classList.toggle('active', on);
    c.setAttribute('aria-pressed', on);
  });
  render();
}

CATS.forEach(cat => {
  const b = document.createElement('button');
  b.className = 'chip' + (cat === state.cat ? ' active' : '');
  b.textContent = cat;
  b.setAttribute('aria-pressed', cat === state.cat);
  b.addEventListener('click', () => setCat(cat));
  chipsEl.appendChild(b);
});

$('#searchInput').addEventListener('input', e => { state.q = e.target.value; render(); });
$('#sortSelect').addEventListener('change', e => { state.sort = e.target.value; render(); });

$('#favBtn').addEventListener('click', () => {
  state.favOnly = !state.favOnly;
  updateFavUI();
  render();
  $('#packs').scrollIntoView({ behavior: 'smooth' });
  showToast(state.favOnly ? '♥ Showing your favorites' : 'Showing all packs');
});

/* category tiles */
const revealIO = new IntersectionObserver(entries => {
  entries.forEach(en => {
    if (!en.isIntersecting) return;
    en.target.classList.add('in');
    revealIO.unobserve(en.target);
  });
}, { threshold: 0.12 });

function buildCatTiles() {
  const grid = $('#catGrid');
  const cats = [...new Set(PACKS.map(p => p.category))];
  cats.forEach((cat, i) => {
    const n = PACKS.filter(p => p.category === cat).length;
    const tile = document.createElement('button');
    tile.className = 'cat-tile reveal';
    tile.style.transitionDelay = (i * 60) + 'ms';
    tile.dataset.cat = cat;
    tile.innerHTML = `<span class="cat-emoji" aria-hidden="true">${PACKS.find(p => p.category === cat).emoji}</span><b>${cat}</b><span class="cat-count">${n} pack${n === 1 ? '' : 's'}</span>`;
    tile.addEventListener('click', () => {
      setCat(cat);
      $('#packs').scrollIntoView({ behavior: 'smooth' });
    });
    grid.appendChild(tile);
    revealIO.observe(tile);
  });
}

/* ---------------- modal ---------------- */

const modal = $('#packModal');
let currentPack = null;

function openModal(p) {
  currentPack = p;
  $('#modalCat').textContent = p.category;
  $('#modalTitle').textContent = p.name;
  $('#modalAdded').textContent = p.added;
  $('#modalDesc').textContent = p.desc;
  $('#modalRes').textContent = p.res || '—';
  $('#modalFormat').textContent = p.format ? 'Format ' + p.format : '—';
  $('#modalSize').textContent = fmtSize(p.bytes);
  $('#modalFile').textContent = p.id + '.zip';

  const media = $('#modalMedia');
  if (p.thumb) {
    media.innerHTML = `<img class="thumb-img" src="${p.thumb}" alt="">`;
  } else {
    media.innerHTML = `<canvas id="modalCanvas" width="12" height="12" aria-hidden="true"></canvas><span class="pack-emoji" aria-hidden="true">${p.emoji}</span>`;
    drawPackTexture($('#modalCanvas'), p);
  }

  const dl = $('#modalDownload');
  dl.href = p.file;
  dl.setAttribute('download', p.name + '.zip');
  dl.dataset.name = p.name;

  updateFavUI();
  modal.hidden = false;
  document.body.classList.add('no-scroll');
  $('.modal-close', modal).focus();
}

function closeModal() {
  modal.hidden = true;
  document.body.classList.remove('no-scroll');
  currentPack = null;
}

modal.addEventListener('click', e => { if (e.target.closest('[data-close]')) closeModal(); });
document.addEventListener('keydown', e => { if (e.key === 'Escape' && !modal.hidden) closeModal(); });

$('#modalFav').addEventListener('click', () => { if (currentPack) toggleFav(currentPack.id); });

/* download feedback: toast + sprinkle burst for every real download link */
document.addEventListener('click', e => {
  const a = e.target.closest('[data-dl]');
  if (!a) return;
  showToast(`⬇ Downloading ${a.dataset.name}.zip …`);
  if (motionOK) sprinkleBurst(e.clientX, e.clientY);
});

function sprinkleBurst(x, y) {
  const colors = ['#ff2ea6', '#29e0e8', '#ffc233', '#9b5cff', '#ff7ac2'];
  for (let i = 0; i < 12; i++) {
    const p = document.createElement('span');
    p.className = 'burst-pill';
    const w = 6 + Math.random() * 9;
    p.style.width = w + 'px';
    p.style.height = Math.round(w * 0.45) + 'px';
    p.style.left = x + 'px';
    p.style.top = y + 'px';
    p.style.background = colors[i % colors.length];
    document.body.appendChild(p);
    const ang = Math.random() * Math.PI * 2;
    const dist = 44 + Math.random() * 70;
    p.animate(
      [
        { transform: 'rotate(0deg)', opacity: 1 },
        {
          transform: `translate(${Math.cos(ang) * dist}px, ${Math.sin(ang) * dist - 22}px) rotate(${Math.round(Math.random() * 300 - 150)}deg)`,
          opacity: 0
        }
      ],
      { duration: 620 + Math.random() * 380, easing: 'cubic-bezier(0.22, 0.61, 0.36, 1)' }
    ).onfinish = () => p.remove();
  }
}

/* ---------------- spotlight ---------------- */

function fillSpotlight() {
  const f = PACKS.find(p => p.featured);
  if (!f) return;
  $('#spotTitle').textContent = f.name;
  $('#spotCat').textContent = f.category;
  $('#spotRes').textContent = f.res || 'zip';
  $('#spotDesc').textContent = f.desc;
  $('#spotRating').textContent = `📦 ${fmtSize(f.bytes)}`;
  $('#spotDl').textContent = f.format ? `🧩 pack format ${f.format}` : '🧩 resource pack';
  $('#spotSize').textContent = `🖼️ ${f.res || 'n/a'} · added ${f.added}`;
  $('#spotList').innerHTML = [
    `📦 ${fmtSize(f.bytes)} — downloads as a ready-to-use .zip`,
    f.format ? `🧩 Pack format ${f.format}` : '🧩 Standard resource pack',
    f.res ? `🖼️ ${f.res} textures` : '🖼️ Interface / font tweaks',
    `📁 Drop the .zip into your .minecraft/resourcepacks folder — no unzipping`
  ].map(x => `<li>${x}</li>`).join('');

  const media = $('#spotMedia');
  if (f.thumb) {
    media.innerHTML = `<img class="thumb-img" src="${f.thumb}" alt="">`;
  } else {
    media.innerHTML = `<canvas id="spotCanvas" width="12" height="12" aria-hidden="true"></canvas><span class="spot-emoji" aria-hidden="true">${f.emoji}</span>`;
    drawPackTexture($('#spotCanvas'), f);
  }

  const dl = $('#spotDownload');
  dl.href = f.file;
  dl.setAttribute('download', f.name + '.zip');
  dl.dataset.name = f.name;
  $('#spotDetails').addEventListener('click', () => openModal(f));
}

/* ---------------- hero: badge, stats, sprinkles, marquee ---------------- */

function fillHero() {
  $('#heroBadge').textContent = `${PACKS.length} free packs · download & play`;
  $('#statPacks').dataset.count = PACKS.length;
}

function makeSprinkles() {
  const field = $('#sprinkleField');
  const colors = ['#ff2ea6', '#29e0e8', '#ffc233', '#9b5cff', '#ff7ac2'];
  for (let i = 0; i < 16; i++) {
    const s = document.createElement('span');
    s.className = 'sprinkle';
    const w = 10 + Math.random() * 18;
    const round = Math.random() < 0.35;
    s.style.width = round ? w * 0.6 + 'px' : w + 'px';
    s.style.height = round ? w * 0.6 + 'px' : w * 0.42 + 'px';
    s.style.borderRadius = '999px';
    s.style.left = Math.random() * 100 + '%';
    s.style.top = Math.random() * 100 + '%';
    s.style.background = colors[i % colors.length];
    s.style.setProperty('--r', Math.floor(Math.random() * 360) + 'deg');
    s.style.animationDuration = 5 + Math.random() * 6 + 's';
    s.style.animationDelay = -Math.random() * 6 + 's';
    field.appendChild(s);
  }
}

function makeMarquee() {
  const words = [...new Set(PACKS.map(p => p.category)), 'Free .zip downloads', 'No login', '16x – 256x'];
  const chunk = words.map(w => `<span>${w}</span>`).join('<i>✦</i>') + '<i>✦</i>';
  $('#marqueeTrack').innerHTML = chunk + chunk;
}

function animateCounters() {
  const io = new IntersectionObserver(entries => {
    entries.forEach(en => {
      if (!en.isIntersecting) return;
      io.unobserve(en.target);
      const el = en.target;
      const target = parseFloat(el.dataset.count) || 0;
      const decimals = el.dataset.count.includes('.');
      const suffix = el.dataset.suffix || '';
      const t0 = performance.now();
      const D = 1300;
      (function tick(t) {
        const k = Math.min(1, (t - t0) / D);
        const e = 1 - Math.pow(1 - k, 3);
        const v = target * e;
        el.textContent = (decimals ? v.toFixed(1) : Math.round(v).toLocaleString('en-US')) + suffix;
        if (k < 1) requestAnimationFrame(tick);
      })(t0);
    });
  }, { threshold: 0.4 });
  $$('[data-count]').forEach(el => io.observe(el));
}

/* ---------------- chrome: header, burger, demo links ---------------- */

const header = $('.site-header');
addEventListener('scroll', () => header.classList.toggle('scrolled', scrollY > 8), { passive: true });

$('#burger').addEventListener('click', () => {
  const nl = $('#navLinks');
  const open = nl.classList.toggle('open');
  $('#burger').setAttribute('aria-expanded', open);
});
$$('#navLinks a').forEach(a => a.addEventListener('click', () => {
  $('#navLinks').classList.remove('open');
  $('#burger').setAttribute('aria-expanded', 'false');
}));

$$('[data-demo]').forEach(el => el.addEventListener('click', e => {
  e.preventDefault();
  showToast('🍩 This is a concept demo — that page is still in the oven.');
}));

/* ---------------- interactivity: tilt, ripple, reveal, scrollspy, parallax ---------------- */

const finePointer = matchMedia('(hover: hover) and (pointer: fine)').matches;
const motionOK = !matchMedia('(prefers-reduced-motion: reduce)').matches;

/* 3D tilt that follows the pointer across pack cards */
if (finePointer && motionOK) {
  grid.addEventListener('pointermove', e => {
    const card = e.target.closest('.pack-card');
    if (!card) return;
    const r = card.getBoundingClientRect();
    const px = (e.clientX - r.left) / r.width - 0.5;
    const py = (e.clientY - r.top) / r.height - 0.5;
    card.style.transform =
      `translateY(-6px) perspective(750px) rotateX(${(-py * 7).toFixed(2)}deg) rotateY(${(px * 7).toFixed(2)}deg)`;
  });
  grid.addEventListener('pointerout', e => {
    const card = e.target.closest('.pack-card');
    if (card && !card.contains(e.relatedTarget)) card.style.transform = '';
  });
}

/* soft ripple inside pixel buttons */
document.addEventListener('click', e => {
  const btn = e.target.closest('.btn-pixel');
  if (!btn || !motionOK) return;
  const r = btn.getBoundingClientRect();
  const x = e.clientX ? e.clientX - r.left : r.width / 2;
  const y = e.clientY ? e.clientY - r.top : r.height / 2;
  const s = document.createElement('span');
  s.className = 'ripple';
  s.style.left = x + 'px';
  s.style.top = y + 'px';
  btn.appendChild(s);
  s.addEventListener('animationend', () => s.remove());
});

/* scroll-reveal for static sections */
$$('[data-reveal]').forEach(el => {
  el.classList.add('reveal');
  revealIO.observe(el);
});

/* highlight the nav link of the section in view */
function initScrollSpy() {
  const links = $$('#navLinks a');
  const map = new Map();
  links.forEach(a => {
    const sec = document.getElementById(a.getAttribute('href').slice(1));
    if (sec) map.set(sec, a);
  });
  const io = new IntersectionObserver(entries => {
    entries.forEach(en => {
      if (!en.isIntersecting) return;
      links.forEach(l => l.classList.remove('active'));
      const a = map.get(en.target);
      if (a) a.classList.add('active');
    });
  }, { rootMargin: '-40% 0px -55% 0px' });
  map.forEach((_, sec) => io.observe(sec));
}

/* hero art leans gently toward the pointer */
function initParallax() {
  if (!finePointer || !motionOK) return;
  const hero = $('.hero');
  const logo = $('.hero-logo');
  const glow = $('.hero-glow');
  const field = $('#sprinkleField');
  let raf = 0;
  hero.addEventListener('pointermove', e => {
    const r = hero.getBoundingClientRect();
    const px = (e.clientX - r.left) / r.width - 0.5;
    const py = (e.clientY - r.top) / r.height - 0.5;
    cancelAnimationFrame(raf);
    raf = requestAnimationFrame(() => {
      logo.style.translate = `${(px * 14).toFixed(1)}px ${(py * 10).toFixed(1)}px`;
      glow.style.translate = `${(px * -18).toFixed(1)}px ${(py * -12).toFixed(1)}px`;
      field.style.translate = `${(px * 8).toFixed(1)}px ${(py * 6).toFixed(1)}px`;
    });
  });
  hero.addEventListener('pointerleave', () => {
    cancelAnimationFrame(raf);
    logo.style.translate = '';
    glow.style.translate = '';
    field.style.translate = '';
  });
}

/* ---------------- init ---------------- */

fillHero();
makeSprinkles();
makeMarquee();
fillSpotlight();
buildCatTiles();
render();
updateFavUI();
animateCounters();
initScrollSpy();
initParallax();
